# name: A TO A:GH_PAGES
# on: # ç›‘å¬ master åˆ†æ”¯ä¸Šçš„ push äº‹ä»¶
#   push:
#     branches:
#       - main
# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest # æ„å»ºç¯å¢ƒä½¿ç”¨ ubuntu
#     steps:
#     - name: Checkout
#       uses: actions/checkout@master

#     - name: Build and Deploy
#       uses: jenkey2011/vuepress-deploy@master
#       env:
#         ACCESS_TOKEN: ${{ secrets.VUEAD }} # VUEAD æ˜¯æˆ‘çš„ secret åç§°ï¼Œéœ€è¦æ›¿æ¢æˆä½ çš„
#         # ä½ è¦æ“ä½œçš„ç›®æ ‡ä»“åº“ï¼Œæ³¨æ„ï¼šæ˜¯é¡¹ç›®ä»“åº“å
#         TARGET_REPO: Janaeiw/vue-beautiful-chat
#         # æ„å»ºç»“æœå­˜å‚¨çš„åˆ†æ”¯
#         TARGET_BRANCH: dist
#         # è¦ä½¿ç”¨çš„æ„å»ºå‘½ä»¤
#         BUILD_SCRIPT: npm install && npm run build # ä¸‹è½½ä¾èµ– æ‰“åŒ…é¡¹ç›®
#         # æ„å»ºç»“æœå­˜å‚¨ç›®å½•ï¼Œdisté‡Œé¢ä¼šæœ‰index.htmlï¼Œå¦‚æœæ²¡æœ‰è¿™ä¸ªæ–‡ä»¶ï¼Œæ˜¾ç¤ºä¸äº†ï¼Œå¯åœ¨æœ¬åœ°æ„å»ºåå»æ ¡éªŒ
#         BUILD_DIR: dist
#   # sync: //giteeé…ç½®
#   #   needs: build-and-deploy
#   #   runs-on: ubuntu-latest
#   #   steps:
#   #   - name: Sync to Gitee
#   #     uses: wearerequired/git-mirror-action@master
#   #     env:
#   #       SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
#   #     with:
#   #       # æ¥æºä»“åº“
#   #       source-repo: "git@github.com:linzowo/linzowo.github.io.git"
#   #       # ç›®æ ‡ä»“åº“
#   #       destination-repo: "git@gitee.com:linzowo/linzowo.git"
#   # reload-pages:
#   #   needs: sync
#   #   runs-on: ubuntu-latest
#   #   steps:
#   #     - name: reload
#   #       uses: mizuka-wu/gitee-pages-action@v1.0.0
#   #       with:
#   #         repository: linzowo/linzowo
#   #         cookie: ${{ secrets.GITEE_COOKIE }}
#   #         branch: gh_pages





name: Build and Deploy
on: 
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: Janaeiw/vue-beautiful-chat@main
        with:
          persist-credentials: false

      - name: Install and Build ğŸ”§ # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          yarn
          yarn build
          cp dist/index.html dist/404.html

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          branch: gh-pages
          folder: dist
